package compiler.parser;

public enum ParseType {
	NULL,
	VARIABLE_DECLARATION,
	FUNCTION_DECLARATION,
	FUNCTION_PARAMATER_DECLARATION,
	FUNCTION_CALL,
	COMMAND,
	COMMAND_WITH_NO_VALUE,
	STATEMENT,
	OPERATION,
	LOGIC
}
